dashboard_tricks:
    resource: "@DashboardTricksBundle/Resources/config/routing.yml"
    prefix:   /

dashboard:
    resource: "@DashboardBundle/Controller/"
    type:     annotation
    prefix:   /dash

tricks:
    resource: "@TricksBundle/Controller/"
    type:     annotation
    prefix:   /tricks

ucfirst:
    resource: "@UcfirstBundle/Resources/config/routing.yml"
    prefix:   /ucfirst

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
